### PR TITLE
Rename datatables

### PR DESCRIPTION
**Pull request by Prakriti-nith**
Rename module DataTables to View. Now DataTable will be created as:

```
Daru::View::DataTable.new(data, options)
```

### CODE REVIEW

**Comment by Prakriti-nith** [comment]
@Shekharrajak  can you please review this PR?

**Comment by Shekharrajak** [comment]
We need to use coveralls  properly, to see the correct coverage report. After that PR will be merged.

**Comment by Prakriti-nith** [comment]
@Shekharrajak ping!

**Comment by Shekharrajak** [comment]
Refer all the changes because of this PR.

**Comment by Prakriti-nith** [comment]
Changes are made to the rails examples in this PR only. Corresponding changes in daru-view are made in this [PR](https://github.com/SciRuby/daru-view/pull/114).

**Comment by Shekharrajak** [comment]
It seems we didn't change the folder structure. :o . It must be inside `daru/view` or `daru/view/datatables` . What do you think ? @Prakriti-nith

**Comment by Prakriti-nith** [comment]
@Shekharrajak I tried changing the folder structure earlier but changing the filename from `data_tables.rb` to `view.rb` or keeping it in view folder generates the following error:
```
uninitialized constant Daru::View::DataTable
```
in rails controller.
So, I reverted back the folder structure to the previous one. I tried it again now too but facing the same problem.

**Comment by Prakriti-nith** [comment]
@Shekharrajak I tried `daru/view/datatables` but when I add the gem in Gemfile of the rails like this:
```
gemspec  :path => '../../'
```
in dummy_rails it throws the error
```
uninitialized constant Daru::View::DataTable
```
However, it is works when I require `daru/view/data_tables` in application_controller.

**Comment by Shekharrajak** [comment]
>  @Prakriti-nith , did you try in console or IRuby notebook ? 

Did you try ?


> However, it is works when I require daru/view/data_tables in application_controller.

I guess you didn't follow this 

> you just have to modify the daru -> data_tables.rb require path accordingly.

**Comment by Shekharrajak** [comment]
Any update? Your conclusion will help me.

**Pull request merged**
